### ISSUE TITLE
CSS host selecting issues

### ISSUE THREAD

**Issue by mtb2112** [Pilatch/easy-element#15] opened 2019-03-22 18:17 UTC
So I have a selector `.pml-select__open .pml-select_list`.  `.pml-select__open` is toggled on/off on the host element when you click the host element.  The demo example that I'm working with works perfectly fine.  But once I bring it into the angular world my gut tells `pml-select__open` is ignored because it is attached to the host element.  I do not see the styling toggling in the dev tools.  All of the toggling of the classes is happening in the markup though.  If I edit the styling in the dist file to be `:host(.pml-select__open) .pml-select-list` for testing purposes, it works fine.

Another issue I found is that for pseudo elements, something funky is happening with the host.  I have the selector in the src of the web component of `pml-select:after`.  Once it is rendered out in the dist folder it is turned into `:host(:after)`.  Again, once I bring it into the angular world, the style is busted.  But once I edit the selector in the dist folder for testing purposes to `:host:after`, it seems to work.

Not sure why it would behave differently outside of the demo page.  Just seems like the shadow root hates me.

**Comment by Pilatch** [comment] 2019-03-25 19:35
I'll have to look into this. For the after pseudo-selector, have you tried using `pml-select::after` with a second colon?  This may be a limitation of the :host selector though.

https://developer.mozilla.org/en-US/docs/Web/CSS/:host()

I'll have to try a simple mock-up that uses `element-name::after` to see what happens myself.

I'm not really sure why going to the angular world would change stuff for you though. I wonder if we could share some simple online angular app thingy that demonstrates the bad behavior.

**Comment by Pilatch** [comment] 2019-03-25 20:30
I have tried to reproduce this on my own without success. If you share your source codez with me I can probably help more.

**Comment by Pilatch** [comment] 2019-03-26 17:29
After some clarification, there is a bug where `element-name::after` gets transformed into `:host(::after)` when instead it should be transformed into `:host::after`.

Another issue is that the documentation could be better when describing the quirks of using shadow DOM where a selector that is intended to target the host element must explicitly target that in class-based land.

**Comment by Pilatch** [comment] 2019-03-26 18:25
Addressed in 1.4.2

**Closed by Pilatch** 2019-03-26 18:25 UTC
Labels: bug, in-progress
